/*
 * PollPal API
 * Your project description
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.55
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The PatchedPollSetAcceptingAnswers model module.
 * @module model/PatchedPollSetAcceptingAnswers
 * @version 1.0.0
 */
export default class PatchedPollSetAcceptingAnswers {
  /**
   * Constructs a new <code>PatchedPollSetAcceptingAnswers</code>.
   * @alias module:model/PatchedPollSetAcceptingAnswers
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>PatchedPollSetAcceptingAnswers</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PatchedPollSetAcceptingAnswers} obj Optional instance to populate.
   * @return {module:model/PatchedPollSetAcceptingAnswers} The populated <code>PatchedPollSetAcceptingAnswers</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PatchedPollSetAcceptingAnswers();
      if (data.hasOwnProperty('poll'))
        obj.poll = ApiClient.convertToType(data['poll'], 'Number');
      if (data.hasOwnProperty('is_accepting_answers'))
        obj.isAcceptingAnswers = ApiClient.convertToType(data['is_accepting_answers'], 'Boolean');
    }
    return obj;
  }
}

/**
 * @member {Number} poll
 */
PatchedPollSetAcceptingAnswers.prototype.poll = undefined;

/**
 * @member {Boolean} isAcceptingAnswers
 */
PatchedPollSetAcceptingAnswers.prototype.isAcceptingAnswers = undefined;

