/*
 * PollPal API
 * Your project description
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.55
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The PollSubmitResponse model module.
 * @module model/PollSubmitResponse
 * @version 1.0.0
 */
export default class PollSubmitResponse {
  /**
   * Constructs a new <code>PollSubmitResponse</code>.
   * @alias module:model/PollSubmitResponse
   * @class
   * @param poll {Number} 
   * @param answer {Number} 
   */
  constructor(poll, answer) {
    this.poll = poll;
    this.answer = answer;
  }

  /**
   * Constructs a <code>PollSubmitResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PollSubmitResponse} obj Optional instance to populate.
   * @return {module:model/PollSubmitResponse} The populated <code>PollSubmitResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PollSubmitResponse();
      if (data.hasOwnProperty('poll'))
        obj.poll = ApiClient.convertToType(data['poll'], 'Number');
      if (data.hasOwnProperty('answer'))
        obj.answer = ApiClient.convertToType(data['answer'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Number} poll
 */
PollSubmitResponse.prototype.poll = undefined;

/**
 * @member {Number} answer
 */
PollSubmitResponse.prototype.answer = undefined;

