/*
 * PollPal API
 * Your project description
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.55
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The PollNextQuestion model module.
 * @module model/PollNextQuestion
 * @version 1.0.0
 */
export default class PollNextQuestion {
  /**
   * Constructs a new <code>PollNextQuestion</code>.
   * @alias module:model/PollNextQuestion
   * @class
   * @param poll {Number} 
   * @param question {Number} 
   */
  constructor(poll, question) {
    this.poll = poll;
    this.question = question;
  }

  /**
   * Constructs a <code>PollNextQuestion</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PollNextQuestion} obj Optional instance to populate.
   * @return {module:model/PollNextQuestion} The populated <code>PollNextQuestion</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PollNextQuestion();
      if (data.hasOwnProperty('poll'))
        obj.poll = ApiClient.convertToType(data['poll'], 'Number');
      if (data.hasOwnProperty('question'))
        obj.question = ApiClient.convertToType(data['question'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Number} poll
 */
PollNextQuestion.prototype.poll = undefined;

/**
 * @member {Number} question
 */
PollNextQuestion.prototype.question = undefined;

