/*
 * PollPal API
 * Your project description
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.55
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import QuestionCreateAnswerInput from './QuestionCreateAnswerInput';

/**
 * The QuestionCreate model module.
 * @module model/QuestionCreate
 * @version 1.0.0
 */
export default class QuestionCreate {
  /**
   * Constructs a new <code>QuestionCreate</code>.
   * @alias module:model/QuestionCreate
   * @class
   * @param prompt {String} 
   * @param answers {Array.<module:model/QuestionCreateAnswerInput>} 
   */
  constructor(prompt, answers) {
    this.prompt = prompt;
    this.answers = answers;
  }

  /**
   * Constructs a <code>QuestionCreate</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/QuestionCreate} obj Optional instance to populate.
   * @return {module:model/QuestionCreate} The populated <code>QuestionCreate</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new QuestionCreate();
      if (data.hasOwnProperty('prompt'))
        obj.prompt = ApiClient.convertToType(data['prompt'], 'String');
      if (data.hasOwnProperty('answers'))
        obj.answers = ApiClient.convertToType(data['answers'], [QuestionCreateAnswerInput]);
    }
    return obj;
  }
}

/**
 * @member {String} prompt
 */
QuestionCreate.prototype.prompt = undefined;

/**
 * @member {Array.<module:model/QuestionCreateAnswerInput>} answers
 */
QuestionCreate.prototype.answers = undefined;

