/*
 * PollPal API
 * Your project description
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.55
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import QuestionCreateAnswerInputRequest from './QuestionCreateAnswerInputRequest';

/**
 * The QuestionCreateRequest model module.
 * @module model/QuestionCreateRequest
 * @version 1.0.0
 */
export default class QuestionCreateRequest {
  /**
   * Constructs a new <code>QuestionCreateRequest</code>.
   * @alias module:model/QuestionCreateRequest
   * @class
   * @param prompt {String} 
   * @param answers {Array.<module:model/QuestionCreateAnswerInputRequest>} 
   */
  constructor(prompt, answers) {
    this.prompt = prompt;
    this.answers = answers;
  }

  /**
   * Constructs a <code>QuestionCreateRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/QuestionCreateRequest} obj Optional instance to populate.
   * @return {module:model/QuestionCreateRequest} The populated <code>QuestionCreateRequest</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new QuestionCreateRequest();
      if (data.hasOwnProperty('prompt'))
        obj.prompt = ApiClient.convertToType(data['prompt'], 'String');
      if (data.hasOwnProperty('answers'))
        obj.answers = ApiClient.convertToType(data['answers'], [QuestionCreateAnswerInputRequest]);
    }
    return obj;
  }
}

/**
 * @member {String} prompt
 */
QuestionCreateRequest.prototype.prompt = undefined;

/**
 * @member {Array.<module:model/QuestionCreateAnswerInputRequest>} answers
 */
QuestionCreateRequest.prototype.answers = undefined;

