/*
 * PollPal API
 * Your project description
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.55
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The QuestionCreateAnswerInput model module.
 * @module model/QuestionCreateAnswerInput
 * @version 1.0.0
 */
export default class QuestionCreateAnswerInput {
  /**
   * Constructs a new <code>QuestionCreateAnswerInput</code>.
   * @alias module:model/QuestionCreateAnswerInput
   * @class
   * @param answer {String} 
   * @param isCorrect {Boolean} 
   */
  constructor(answer, isCorrect) {
    this.answer = answer;
    this.isCorrect = isCorrect;
  }

  /**
   * Constructs a <code>QuestionCreateAnswerInput</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/QuestionCreateAnswerInput} obj Optional instance to populate.
   * @return {module:model/QuestionCreateAnswerInput} The populated <code>QuestionCreateAnswerInput</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new QuestionCreateAnswerInput();
      if (data.hasOwnProperty('answer'))
        obj.answer = ApiClient.convertToType(data['answer'], 'String');
      if (data.hasOwnProperty('is_correct'))
        obj.isCorrect = ApiClient.convertToType(data['is_correct'], 'Boolean');
    }
    return obj;
  }
}

/**
 * @member {String} answer
 */
QuestionCreateAnswerInput.prototype.answer = undefined;

/**
 * @member {Boolean} isCorrect
 */
QuestionCreateAnswerInput.prototype.isCorrect = undefined;

