/*
 * PollPal API
 * Your project description
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.55
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The Response model module.
 * @module model/Response
 * @version 1.0.0
 */
export default class Response {
  /**
   * Constructs a new <code>Response</code>.
   * @alias module:model/Response
   * @class
   * @param id {Number} 
   * @param poll {Number} 
   * @param answer {Number} 
   */
  constructor(id, poll, answer) {
    this.id = id;
    this.poll = poll;
    this.answer = answer;
  }

  /**
   * Constructs a <code>Response</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Response} obj Optional instance to populate.
   * @return {module:model/Response} The populated <code>Response</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Response();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('poll'))
        obj.poll = ApiClient.convertToType(data['poll'], 'Number');
      if (data.hasOwnProperty('answer'))
        obj.answer = ApiClient.convertToType(data['answer'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
Response.prototype.id = undefined;

/**
 * @member {Number} poll
 */
Response.prototype.poll = undefined;

/**
 * @member {Number} answer
 */
Response.prototype.answer = undefined;

