/*
 * PollPal API
 * Your project description
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.55
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The SessionStartRequest model module.
 * @module model/SessionStartRequest
 * @version 1.0.0
 */
export default class SessionStartRequest {
  /**
   * Constructs a new <code>SessionStartRequest</code>.
   * @alias module:model/SessionStartRequest
   * @class
   * @param session {Number} 
   * @param question {Number} 
   */
  constructor(session, question) {
    this.session = session;
    this.question = question;
  }

  /**
   * Constructs a <code>SessionStartRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SessionStartRequest} obj Optional instance to populate.
   * @return {module:model/SessionStartRequest} The populated <code>SessionStartRequest</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new SessionStartRequest();
      if (data.hasOwnProperty('session'))
        obj.session = ApiClient.convertToType(data['session'], 'Number');
      if (data.hasOwnProperty('question'))
        obj.question = ApiClient.convertToType(data['question'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Number} session
 */
SessionStartRequest.prototype.session = undefined;

/**
 * @member {Number} question
 */
SessionStartRequest.prototype.question = undefined;

