/*
 * PollPal API
 * Your project description
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.55
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The SessionRequest model module.
 * @module model/SessionRequest
 * @version 1.0.0
 */
export default class SessionRequest {
  /**
   * Constructs a new <code>SessionRequest</code>.
   * @alias module:model/SessionRequest
   * @class
   * @param label {String} 
   */
  constructor(label) {
    this.label = label;
  }

  /**
   * Constructs a <code>SessionRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SessionRequest} obj Optional instance to populate.
   * @return {module:model/SessionRequest} The populated <code>SessionRequest</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new SessionRequest();
      if (data.hasOwnProperty('label'))
        obj.label = ApiClient.convertToType(data['label'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} label
 */
SessionRequest.prototype.label = undefined;

