/*
 * PollPal API
 * Your project description
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.55
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PollPalApi);
  }
}(this, function(expect, PollPalApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('Poll', function() {
      beforeEach(function() {
        instance = new PollPalApi.Poll();
      });

      it('should create an instance of Poll', function() {
        // TODO: update the code to test Poll
        expect(instance).to.be.a(PollPalApi.Poll);
      });

      it('should have the property id (base name: "id")', function() {
        // TODO: update the code to test the property id
        expect(instance).to.have.property('id');
        // expect(instance.id).to.be(expectedValueLiteral);
      });

      it('should have the property is_accepting_answers (base name: "is_accepting_answers")', function() {
        // TODO: update the code to test the property is_accepting_answers
        expect(instance).to.have.property('is_accepting_answers');
        // expect(instance.is_accepting_answers).to.be(expectedValueLiteral);
      });

      it('should have the property session (base name: "session")', function() {
        // TODO: update the code to test the property session
        expect(instance).to.have.property('session');
        // expect(instance.session).to.be(expectedValueLiteral);
      });

    });
  });

}));
