/*
 * PollPal API
 * Your project description
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.55
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from './ApiClient';
import PatchedPollSetAcceptingAnswers from './model/PatchedPollSetAcceptingAnswers';
import PollNextQuestion from './model/PollNextQuestion';
import PollSetAcceptingAnswers from './model/PollSetAcceptingAnswers';
import PollSubmitResponse from './model/PollSubmitResponse';
import QuestionCreate from './model/QuestionCreate';
import QuestionCreateAnswerInput from './model/QuestionCreateAnswerInput';
import Session from './model/Session';
import SessionStart from './model/SessionStart';
import PollApi from './api/PollApi';
import QuestionApi from './api/QuestionApi';
import SessionApi from './api/SessionApi';

/**
* Your_project_description.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var PollPalApi = require('index'); // See note below*.
* var xxxSvc = new PollPalApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new PollPalApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new PollPalApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new PollPalApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The PatchedPollSetAcceptingAnswers model constructor.
     * @property {module:model/PatchedPollSetAcceptingAnswers}
     */
    PatchedPollSetAcceptingAnswers,

    /**
     * The PollNextQuestion model constructor.
     * @property {module:model/PollNextQuestion}
     */
    PollNextQuestion,

    /**
     * The PollSetAcceptingAnswers model constructor.
     * @property {module:model/PollSetAcceptingAnswers}
     */
    PollSetAcceptingAnswers,

    /**
     * The PollSubmitResponse model constructor.
     * @property {module:model/PollSubmitResponse}
     */
    PollSubmitResponse,

    /**
     * The QuestionCreate model constructor.
     * @property {module:model/QuestionCreate}
     */
    QuestionCreate,

    /**
     * The QuestionCreateAnswerInput model constructor.
     * @property {module:model/QuestionCreateAnswerInput}
     */
    QuestionCreateAnswerInput,

    /**
     * The Session model constructor.
     * @property {module:model/Session}
     */
    Session,

    /**
     * The SessionStart model constructor.
     * @property {module:model/SessionStart}
     */
    SessionStart,

    /**
    * The PollApi service constructor.
    * @property {module:api/PollApi}
    */
    PollApi,

    /**
    * The QuestionApi service constructor.
    * @property {module:api/QuestionApi}
    */
    QuestionApi,

    /**
    * The SessionApi service constructor.
    * @property {module:api/SessionApi}
    */
    SessionApi
};
