# Generated by Django 5.0.4 on 2024-05-01 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("session", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="response",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="session.response",
            ),
        ),
    ]
