# Generated by Django 5.0.1 on 2024-02-04 02:59

from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_id', models.IntegerField(primary_key=True, serialize=False)),
                ('session_label', models.CharField(max_length=255)),
            ],
        ),
    ]