# Generated by Django 5.0.4 on 2024-04-26 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0002_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='questionID',
            new_name='question_id',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_text',
        ),
        migrations.RemoveField(
            model_name='question',
            name='session',
        ),
        migrations.AddField(
            model_name='question',
            name='prompt',
            field=models.CharField(default='', max_length=4095),
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('poll_id', models.IntegerField(primary_key=True, serialize=False)),
                ('question_id', models.IntegerField(default=-1)),
                ('is_accepting_answers', models.BooleanField(default=False)),
                ('related_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_polls', to='session.question')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='session.session')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='related_poll',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='related_questions', to='session.poll'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('response_id', models.IntegerField(primary_key=True, serialize=False)),
                ('prompt', models.CharField(default='', max_length=4095)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='session.question')),
            ],
        ),
    ]
