/*
 * PollPal API
 * Your project description
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.55
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from "../ApiClient";
import QuestionCreate from '../model/QuestionCreate';
import QuestionCreateAnswerInput from '../model/QuestionCreateAnswerInput';

/**
* Question service.
* @module api/QuestionApi
* @version 1.0.0
*/
export default class QuestionApi {

    /**
    * Constructs a new QuestionApi. 
    * @alias module:api/QuestionApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the questionCreateCreate operation.
     * @callback moduleapi/QuestionApi~questionCreateCreateCallback
     * @param {String} error Error message, if any.
     * @param {module:model/QuestionCreate{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Creates a question with the provided prompt and answers.
     * @param {module:model/QuestionCreate} body 
     * @param {String} prompt 
     * @param {Array.<module:model/QuestionCreateAnswerInput>} answers 
     * @param {String} prompt 
     * @param {Array.<module:model/QuestionCreateAnswerInput>} answers 
     * @param {module:api/QuestionApi~questionCreateCreateCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    questionCreateCreate(body, prompt, answers, prompt, answers, callback) {
      
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling questionCreateCreate");
      }
      // verify the required parameter 'prompt' is set
      if (prompt === undefined || prompt === null) {
        throw new Error("Missing the required parameter 'prompt' when calling questionCreateCreate");
      }
      // verify the required parameter 'answers' is set
      if (answers === undefined || answers === null) {
        throw new Error("Missing the required parameter 'answers' when calling questionCreateCreate");
      }
      // verify the required parameter 'prompt' is set
      if (prompt === undefined || prompt === null) {
        throw new Error("Missing the required parameter 'prompt' when calling questionCreateCreate");
      }
      // verify the required parameter 'answers' is set
      if (answers === undefined || answers === null) {
        throw new Error("Missing the required parameter 'answers' when calling questionCreateCreate");
      }

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        'prompt': prompt,'answers': this.apiClient.buildCollectionParam(answers, 'multi'),'prompt': prompt,'answers': this.apiClient.buildCollectionParam(answers, 'multi')
      };

      let authNames = ['basicAuth', 'cookieAuth'];
      let contentTypes = ['application/json', 'application/x-www-form-urlencoded', 'multipart/form-data'];
      let accepts = ['application/json'];
      let returnType = QuestionCreate;

      return this.apiClient.callApi(
        '/api/question/create', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}